# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e539fd25d57f5d8ec1fe10d988f57e801177df7f7b3022a8ef3d30b67e71d838790e6d79cf4c98df2409313e9467b8005f45235372037aa48a28bf967ce5e871

test:
  secret_key_base: 11d9e095c50a8d4d6db0030d1e9f01aad5445deb58cafc8fa3e44833d83f2525930168164eb05491c20eb5ad60cf73666e4142633ef8d00ae78426cd9ed63227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
